version: '3.7'
services:
  mysqldb:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  mysqldb_data: