version: '3.7'
services:
  postgresdb:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: fastdb
      POSTGRES_PASSWORD: fastdbpass
      POSTGRES_DB: testdb
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 127.0.0.1:5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fastdb@fastdb.com
      PGADMIN_DEFAULT_PASSWORD: fastdbpass
      PGADMIN_LISTEN_PORT: 80
    ports:
    - 5050:80
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - postgresdb:pgsql-server
volumes:
  db-data: null
  pgadmin-data: null
