version: '3.7'
services:
  postgresdb:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: fastdb
      POSTGRES_PASSWORD: fastdbpass
      POSTGRES_DB: testdb
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 127.0.0.1:5432:5432
volumes:
  db-data: null
  pgadmin-data: null
