version: '3.7'
services:
  mysqldb:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: roottestpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: fs2db
      MYSQL_PASSWORD: fs2dbpassword
    ports:
    - 127.0.0.1:33061:3306
    volumes:
    - mysqldb_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
    - 8080:8080
volumes:
  mysqldb_data: null
