version: '3.7'
services:
  mysqldb:
    image: mysql:5.7
    command: --max_allowed_packet=32505856 --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: fastdbrootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: fastdb
      MYSQL_PASSWORD: fastdbpass
    ports:
      - 127.0.0.1:33061:3306
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  mysqldb_data: